config/routes.rb
Rails.application.routes.draw do
  resources :games, except: [:edit, :update, :delete]
  get '/games/:id/play', to: 'games#edit', as: 'game_play'
  patch '/games/:id/play', to: 'games#update', as: 'update_game_play'

  root :to => "static#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :turns

  def selected_board_index
  end

  def board
    board = []
    self.turns.each do |turn|
      board[turn.board_index] = turn.mark if turn.board_index
    end

    return board
  end

  def get_mark_for_turn
    if self.turns.size % 2 == 0
      return 'X'
    else
      return 'O'
    end
  end

  def get_turn_history
    # Get cumulative turn history
    sum = []
    history = []
    self.turns.first(9).each_with_index do |turn, i|   
      sum << turn
      sum.each do |t|
        history[i] ||= []
        history[i] << t
      end
    end

    history
  end
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @history = @game.get_turn_history
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(create_params)

    # Randomize who starts in single player
    if @game.is_single_player
      # AI start
      if [true,false].sample
        do_move(@game, @game.get_mark_for_turn)
      end
    end

    redirect_to game_play_path(@game)
  end
  
  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    player_mark = @game.get_mark_for_turn

    # Player move
    @game.turns.build(
      mark: player_mark,
      board_index: update_params[:selected_board_index]
    ).save

    # Check for win by player
    result = check_for_win(@game)
    if !result
      # AI move
      if @game.is_single_player
        do_move(@game, get_other_mark(player_mark))
      end
    end

    # Check for win by AI
    result ||= check_for_win(@game)
    # If game has ended, go to :show
    if result
      @game.update(victor: result[0], win: result[1])
      redirect_to game_path(@game)
    # If no win, keep showing :edit
    else
      redirect_to game_play_path(@game)
    end
  end

  private

  def update_params
    params.require(:game).permit(:selected_board_index)
  end

  def create_params
    params.require(:game).permit(:is_single_player)
  end

  def get_other_mark(mark)
    mark == 'X' ? 'O' : 'X'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  @@win_conditions = [
    # Rows
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    # Columns
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    # Diagonals
    [0, 4, 8],
    [2, 4, 6]
  ]

  # Returns an array with 'X' or 'O' and string of winning combo if there is a winner
  # or 'TIE' and an empty string if game ended with no winners
  # or nil if game has not yet ended
  def check_for_win(game)
    return nil if game.turns.size < 5 

    xs = game.turns.where(mark: 'X').map {|turn| turn.board_index }
    os = game.turns.where(mark: 'O').map {|turn| turn.board_index }

    @@win_conditions.each do |win|
      # Check if xs or os contain indices combo that meet win condition
      if (win-xs).empty?
        return ["X", win.join(' ')]
      elsif (win-os).empty?
        return ["O",win.join(' ')]
      end
    end

    if game.turns.size > 8
      return ["TIE",""]
    else
      return nil
    end
  end

  # AI Logic
  # 1. If there's two in a row, get the third for the win
  # 2. If player has two in a row, block the third
  # 3. Get a corner
  # 4. Get the center
  def do_move(game, mark)
    player = mark == 'X' ? 'O' : 'X'
    player_marks = game.turns.where(mark: player).map {|turn| turn.board_index}
    marks = game.turns.where(mark: mark).map {|turn| turn.board_index}
    i = nil

    # Look for winning move
    @@win_conditions.each do |win|
      if (win-marks).size == 1 && !game.board[(win-marks).first]
        i = (win-marks).first
      end
    end

    if !i
      # Block any potential wins for player
      @@win_conditions.each do |win|
        if (win-player_marks).size == 1 && !game.board[(win-player_marks).first]
          i = (win-player_marks).first
        end
      end
    end

    if !i
      # Prioritize corners 
      if !game.board[0] || !game.board[2] || !game.board[6] || !game.board[8]
        i = [0, 2, 6, 8].sample 

        while game.board[i]
          i = [0, 2, 6, 8].sample 
        end
      # Else prioritize center
      elsif !game.board[4]
        i = 4
      end
    end

    # If all else fails just pick a random open spot
    if !i
      i = [1, 3, 5, 7].sample

      while game.board[i]
        i = [1, 3, 5, 7].sample 
      end
    end

    game.turns.build(mark: mark, board_index: i).save
  end
end

app/views/games/edit.erb
<div class="center game-board">
  <% [0, 3, 6].each do |i| %>
    <div class="row">
      <% (0..2).each do |j| %>
        <div class="square board-<%= i+j %>">
          <% if !@game.board[i+j] %>
            <%= form_for @game, url: update_game_play_path(@game) do |f| %>
              <%= f.submit '', class: "board-button" %>
              <%= f.hidden_field :selected_board_index, value: i+j %>
            <% end %>
          <% else %>
            <div class="mark <%= @game.board[i+j] %>">
              <%= @game.board[i+j] %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<h1 class="center">
  <span class="<%= @game.get_mark_for_turn %>"><%= @game.get_mark_for_turn %></span>'s Turn
</h1>

app/views/games/index.erb
<h1>Played Games</h1>
<ul>
  <% @games.each do |game| %>
    <li><%= link_to game.is_single_player ? "Game #{game.id} - vs AI" : "Game #{game.id} - vs Player", game %></  li>
  <% end %>
</ul>
<p>
  <%= button_to "Back to Main Menu", :root, :method => "get", :class => "button" %>
</p>

app/views/games/new.erb
<div class="center game-board">
  <div class="row">
    <div class="square board-0">T</div><div class="square board-1">I</div><div class="square board-2">C</div>
  </div>
  <div class="row"> 
    <div class="square board-3">T</div><div class="square board-4">A</div><div class="square board-5">C</div>
  </div>
  <div class="row"> 
    <div class="square board-6">T</div><div class="square board-7">O</div><div class="square board-8">E</div>
  </div>
</div>

<div class="center">
  <%= form_for(@game) do |f| %>
  <%= f.hidden_field :is_single_player, value: true %>
    <%= f.submit 'Single Player', class: "button" %>
  <% end %>
  <%= form_for(@game) do |f| %>
      <%= f.hidden_field :is_single_player, value: false %>
    <%= f.submit 'Two Players', class: "button" %>
  <% end %>
  <br>
    
    <%= button_to "Back to Main Menu", :root, :method => "get", :class => "button" %>

</div>

app/views/games/show.erb
<div class="center game-board">
  <% [0, 3, 6].each do |i| %>
    <div class="row">
      <% (0..2).each do |j| %>
        <div class="square board-<%= i+j %>">
          <% if @game.board[i+j] %>
            <div class="mark <%= @game.board[i+j] %> <%= "win" if @game.win && @game.win.split(' ').include?((i+j).to_s) %>">
              <%= @game.board[i+j] %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if @game.victor %>
  <h1 class="center">
    <% if @game.victor == "TIE" %>
      <span class="<%= @game.victor %>"><%= @game.victor %></span>
    <% else %>
      Winner: <span class="<%= @game.victor %>"><%= @game.victor %></span>
    <% end %>
  </h1>
<% else %>
  <div class="center">
    <%= button_to "Resume Play", game_play_path(@game), :method => "get", :class => "button" %>
  </div>

<% end %>
<br>
<div class="center">
<%= button_to "New Game", :new_game, :method => "get", :class => "button" %>
  <%= button_to "Back to Main Menu", :root, :method => "get", :class => "button" %>
</div>
<br>
<hr>
<h3>Turn History</h3>
<% @history.each_with_index do |turns, idx| %>
  <h4 class="turn-history">&nbsp;<%= "#{idx+1}. "%>
    <div class="game-board minified">
      <% [0, 3, 6].each do |i| %>
        <div class="row">
          <% (0..2).each do |j| %>
            <div class="square board-<%= i+j %>">
              <% turns.each do |turn| %>
                <% if i+j == turn.board_index %>
                  <div class="mark <%= turn.mark %>">
                    <%= turn.mark %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </h4>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFormsTicTacToe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>